[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/mailgun/mailgun-go"
  version = "2.0.0"

[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  version = "1.0.2"
